# T4.1 配置文件 - 根据 train_single.py 的 argparse 默认值生成

# 常用训练参数
tensorboard_log: './logs'
experiment_name: 'Single-Vertical-R4.7.0'
model_dir: './results/Single-Vertical-R4.7.0'
leaner_name: 'R4.7.0_W2E4_T4.1_fragile'
remark: 'T4.1 全任务微调到fragile'
cargo_type: 'fragile'
total_steps: 60000
pretrained_model_path: './results/Single-Vertical-R4.7.0/R4.7.0_W2E4_T6.1/td3_R4.7.0_W2E4_T6.1.zip'
world_1: '../warehouse/worlds/warehouse2_end5.wbt'
training_mode: 'vertical_curriculum'

# 绘图参数
plot_vmin: -100.0
plot_vmax: 100.0

# 基本参数
device: 'cuda'
seed: 0

# 环境参数
obs_mode: 'lidar'
action_mode: 'wheels'
macro_action_steps: 1
enable_speed_smoothing: false
control_period_ms: 200

# Webots参数
headless: true
fast_mode: true
no_rendering: true
batch: true
minimize: true

# UI参数
show_ui: false
show_map: false
display_plot: false
debug: false

# TD3参数
learning_rate: 0.0003
buffer_size: 50000
learning_starts: 2000
batch_size: 256
gamma: 0.99
tau: 0.005
train_freq: 1
gradient_steps: 1
policy_delay: 2
exploration_noise_init: 0.1
target_policy_noise_init: 0.05
target_noise_clip_init: 0.2

# 日志参数
verbose: 1
log_interval: 100
mlflow_log_interval: 500
step_avg_window: 1000
draw_trajectory: true

# 障碍物与课程学习参数
enable_obstacle_curriculum: false
use_predefined_positions: false
fixed_obstacle_count: -1
lock_obstacles_per_stage: true
obstacle_curriculum_steps: [0, 10000, 20000, 32000, 46000, 60000, 76000, 94000, 113000, 132000, 153000, 174000]
obstacle_curriculum_counts: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

# 继续训练参数
reset_num_timesteps: false

# 课程学习参数（兼容性）
curriculum_stage: 'end'

# 奖励系数参数
delta_distance_k: 30.0
movement_reward_k: 0.5
liner_distance_reward: 0
distance_k: 0.7
time_k: 0.4
wall_proximity_penalty_k: 3.0
angle_reward_k: 5.0
angle_change_k: 15.0
directional_movement_k: 50.0
early_spin_penalty_k: 1.0
front_clear_k: 1.0

# 停用奖励
stop_bonus_k: 0.0
approach_reward_k: 0.0
slow_down_reward_k: 0.0